# Docker Compose file of the Program. Change contianer settings here.
# (Any port changes must be done here and the "Dockerfile " and ".env")

services:
  # Container for web app:
  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT}
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}" # Expose
    volumes:
      - app_data:/app/data
    depends_on: # Starts when database is ready
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://web:${FASTAPI_PORT}/health')"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  # Scrapers:
  scraper:
    build:
      context: .
    command: /usr/local/bin/supercronic /app/scripts/scraper.crontab --passthrough-logs # Run crontab
    env_file:
      - .env
    volumes:
      - scraper_data:/app/status_scraper
    depends_on: # When web starts
      web:
        condition: service_healthy
    restart: unless-stopped

  # PostgreSQL:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /opt/mesonet-backups:/backups:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mesonet -d mesonet"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  # Postgre SQL Backups (https://github.com/prodrigestivill/docker-postgres-backup-local)
  db_backup:
    image: prodrigestivill/postgres-backup-local:16
    restart: unless-stopped
    env_file:
      - .env
    enviroment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Run on container start:
      BACKUP_ON_START: "TRUE"

      # Run daily at 2:15 AM
      SCHEDULE: "@daily"

      # Keep exactly requested retention:
      BACKUP_KEEP_DAYS: ${BACKUP_KEEP_DAYS}
      BACKUP_KEEP_WEEKS: ${BACKUP_KEEP_WEEKS}
      BACKUP_KEEP_MONTHS: ${BACKUP_KEEP_MONTHS}
      BACKUP_KEEP_YEAR: ${BACKUP_KEEP_YEAR}

      HEALTHCHECK_PORT: 8080

    volumes:
      - /opt/mesonet-backups:/backups
    depends_on:
      db:
        condition: service_healthy

  health-tests:
    build:
      context: .
    command: /usr/local/bin/supercronic /app/scripts/health.crontab --passthrough-logs # Run health checks
    env_file:
      - .env
    volumes:
      - /opt/mesonet-backups:/backups
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  app_data:
  scraper_data: